"""Add rating and review to UserBook model

Revision ID: 21ab5f2fa886
Revises: 18193fa55da6
Create Date: 2024-10-03 13:59:01.936552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ab5f2fa886'
down_revision = '18193fa55da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.drop_column('review')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
