"""Add image_url to Author model

Revision ID: 663b06fcb7dc
Revises: 
Create Date: 2024-09-28 14:46:34.739895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663b06fcb7dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_book_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
