"""Add Google Books API fields

Revision ID: a2b110b1858d
Revises: cf403bec3630
Create Date: 2024-09-23 15:00:47.970596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b110b1858d'
down_revision = 'cf403bec3630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('published_date', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('published_date')
        batch_op.drop_column('page_count')
        batch_op.drop_column('cover_image_url')
        batch_op.drop_column('description')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
