"""Change is_read to read_date in UserBook model

Revision ID: ae81fdad3e5e
Revises: 21ab5f2fa886
Create Date: 2024-10-03 14:25:40.345300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae81fdad3e5e'
down_revision = '21ab5f2fa886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_date', sa.Date(), nullable=True))
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('read_date')

    # ### end Alembic commands ###
