"""Add is_main_work field to Book model

Revision ID: d33a346b26df
Revises: 8f6c6c4dc68e
Create Date: 2024-09-26 14:45:45.508981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33a346b26df'
down_revision = '8f6c6c4dc68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_main_work', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('is_main_work')

    # ### end Alembic commands ###
