"""Add multilingual support

Revision ID: da2aa1cc6a9e
Revises: 46e03495dad1
Create Date: 2024-10-05 06:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da2aa1cc6a9e'
down_revision = '46e03495dad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
